### ISSUE TITLE
Invalid tasks are accepted

### ISSUE THREAD

**Issue by seetohjinwei** [AY2223S1-CS2103T-T13-4/tp#141]
If a task contains a name that is not in the contact list (e.g. user edits the taskbook.json file directly), it is still parsed as if there is no issue, which results in the task being associated to a ghost.

Perhaps, an error should be thrown and the task list be reset?

**Comment by dexter-sim** [comment]
Adding a task with a name that does not exist in the contact list will present a `Person not found in task book!` message.

**Comment by xiaobill8** [comment]
Implement a manual save feature to a diff JSON file, if autosave json is corrupted, try to reload from manual save file, otherwise, throw new error (implement a check if all Tasks match a Person after readTaskBook)
