### ISSUE TITLE
[PE-D][Tester C] Deadline Bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-4/tp#211]
# Title: Deadline Bug

## Steps To Reproduce Bug

1. Command `task deadline m/Alex Yeoh d/Buy Milk t/1990-02-12`

## Why I think this is a bug
- I don't think that when adding deadlines they should be allowed to be in the past.

## Screenshots

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: johnbenedictyan/ped#4

**Comment by seetohjinwei** [comment]
Intended as there are legitimate reasons to add a date in the past.
