### ISSUE TITLE
[PE-D][Tester C] Date Format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T13-4/tp#213]
- The application should state the valid date formats that you can add in the commands or help to parse `2024-2-29` to `2024-02-29` or `24 feb 2012` to `24 Feb 2012`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: johnbenedictyan/ped#6

**Comment by seetohjinwei** [comment]
Won't update, but for UG, will add a navigation link to our accepted date formats section in task creation section.

**Comment by dexter-sim** [comment]
Has been resolved in #245.
