### ISSUE TITLE
[PE-D][Tester C] Help text does not appear for incorrect edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T13-4/tp#214]
# Title: Help text does not appear for the incorrect edit command

## Steps To Reproduce Bug

1. Command `task edit i/-1` or `contact edit i/-1`

## Why I think this is a bug
- The application does not show the help command even though it is an erroneous command

## Screenshots

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: johnbenedictyan/ped#7

**Comment by seetohjinwei** [comment]
Fix and handle negative indices.
